from typing import List, Dict
from pathlib import Path
import json
from datetime import datetime


class HTMLGenerator:
    def __init__(self, output_dir: str = "output"):
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(exist_ok=True)

    def generate_html(self, repo_data_list: List[Dict]) -> str:
        """生成展示仓库数据的 HTML 页面"""

        # 生成仓库数据的 JSON 字符串
        repos_json = json.dumps(repo_data_list, ensure_ascii=False)

        html_content = f"""
<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GitHub Trending 分析报告</title>
    
    <!-- 使用 Element Plus -->
    <link rel="stylesheet" href="https://unpkg.com/element-plus/dist/index.css">
    <script src="https://unpkg.com/vue@3/dist/vue.global.js"></script>
    <script src="https://unpkg.com/element-plus"></script>
    
    <style>
        body {{ 
            margin: 0;
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
        }}
        .container {{ 
            max-width: 1200px; 
            margin: 0 auto; 
            padding: 20px;
        }}
        .header {{
            background: #fff;
            padding: 20px;
            box-shadow: 0 2px 4px rgba(0,0,0,.1);
            margin-bottom: 20px;
        }}
        .header h1 {{
            margin: 0;
            font-size: 24px;
            color: #333;
        }}
        .header p {{
            margin: 10px 0 0;
            color: #666;
        }}
        .repo-card {{
            margin-bottom: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 12px 0 rgba(0,0,0,.1);
        }}
        .tag {{
            margin-right: 8px;
            margin-bottom: 8px;
        }}
        .footer {{
            text-align: center;
            padding: 20px;
            color: #666;
            font-size: 14px;
        }}
    </style>
</head>
<body>
    <div id="app">
        <div class="header">
            <h1>GitHub Trending 分析报告</h1>
            <p>生成时间：{datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>
        </div>
        
        <div class="container">
            <el-card v-for="repo in repos" :key="repo.url" class="repo-card">
                <template #header>
                    <div style="display: flex; align-items: center; justify-content: space-between">
                        <a :href="repo.url" target="_blank" style="color: #409EFF; text-decoration: none; font-size: 18px; font-weight: bold;">
                            {{{{ repo.name }}}}
                        </a>
                        <el-tag type="info">{{{{ repo.stars }}}} stars</el-tag>
                    </div>
                </template>
                
                <el-descriptions :column="1" border>
                    <el-descriptions-item label="项目简介">
                        {{{{ repo.summary }}}}
                    </el-descriptions-item>
                    <el-descriptions-item label="技术标签">
                        <el-tag 
                            v-for="tag in repo.tech_tags" 
                            :key="tag"
                            class="tag"
                            type="success"
                        >{{{{ tag }}}}</el-tag>
                    </el-descriptions-item>
                    <el-descriptions-item label="应用领域">
                        <el-tag 
                            v-for="tag in repo.domain_tags" 
                            :key="tag"
                            class="tag"
                            type="warning"
                        >{{{{ tag }}}}</el-tag>
                    </el-descriptions-item>
                </el-descriptions>
            </el-card>
        </div>
        
        <div class="footer">
            Generated by GitHub Trending Analyzer
        </div>
    </div>

    <script>
        const {{ createApp }} = Vue;
        const repos = {repos_json};
        
        const app = createApp({{
            data() {{
                return {{
                    repos: repos
                }}
            }}
        }});
        app.use(ElementPlus);
        app.mount('#app');
    </script>
</body>
</html>
        """

        # 生成文件名
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        output_file = self.output_dir / f"trending_report_{timestamp}.html"

        # 写入文件
        output_file.write_text(html_content, encoding="utf-8")

        return str(output_file)
